---
apiVersion: apps/v1

kind: Deployment

metadata:
  name: github-gql

  labels:
    app: web

spec:
  replicas: 4

  selector:
    matchLabels:
      app: web

  template:
    metadata:
      labels:
        app: web

    spec:
      containers:
        - name: github-gql-back

          image: gharbiamine/github-gql-back:latest

          ports:
            - containerPort: 3001
          env:
            - name: GITHUB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: github-gql-secret
                  key: GITHUB_API_KEY

        - name: github-gql-front

          image: gharbiamine/github-gql:0.1.1

          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: github-gql-front-service
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: github-gql-back-service
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 3001
      targetPort: http

---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
    app: web
spec:
  selector:
    app: web
  ports:
    - port: 5173
      targetPort: 5173
      nodePort: 30001
      protocol: TCP
  type: LoadBalancer
