apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
    app: web
spec:
  selector:
    app: web
  ports:
    - port: 4173
      targetPort: 4173
      nodePort: 30001
      protocol: TCP
  type: LoadBalancer
